version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=clustereddatawarehouse
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  app-server:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clustereddatawarehouse?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    build:
      context: target
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "8099"
    command: mvn clean spring-boot:run
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - db
    volumes:
      - ~/.m2:/root/.m2
      - .:/app
